<?php
namespace app\admin\controller;

use app\common\controller\AdminBase;
use think\Loader;

class Upload extends AdminBase
{
    protected $upFile;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->upFile = Loader::model('Upload','service');
    }

    public function upload()
	{
//	    phpinfo();die;
	    $info = $this->upFile->uploadFile('file','',500,400,100,100);
	    return $info;
	}
}
